include: package:flutter_lints/flutter.yaml

linter:
  rules:
    depend_on_referenced_packages: false
    use_build_context_synchronously: false

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 60

  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - no-equal-then-else